gameforge.map_warp = {}
gameforge.map_warp._180_select = "ãäØŞÉ íæäÛÇä "
gameforge.map_warp._190_select = "ãŞÇØÚÉ íÇíÇäÛ "
gameforge.map_warp._200_select = "ãäØŞÉ ÌæÇä "
gameforge.map_warp._210_select = "ãäØŞÉ ÈæßíæäÛ "
gameforge.map_warp._220_select = "ãäØŞÉ ÈíæäÛãæ "
gameforge.map_warp._230_select = "ãŞÇØÚÉ ÈóßÑÇ "
gameforge.map_warp._98_stringFormat = "ÚÏÏ ÇáÊäŞáÇÊ ÇáãÊÈŞíÉ:%d "
gameforge.locale.cancel = "ÅáÛÇÁ "